site_name: s3gw Documentation
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
nav:
  - 'Getting started':
    - Welcome: 'index.md'
    - Quickstart: 'quickstart.md'
  - 'Developing the s3gw':
    - Developing the S3 Gateway: 'developing.md'
    - Using a Helm chart: 'helm-charts.md'
    - Testing the s3gw: 'testing.md'
    - S3 API compatibility table: 's3-compatibility-table.md'
  - 'Build a container':
    - Building the s3gw container image: 'build.md'
    - Building the s3gw-UI image: 'build-ui.md'
  - 'Running the s3gw with Longhorn':
    - K3s Setup: 'env-k3s.md'
    - K8s Setup: 'env-k8s.md'
  - 'About & Contributing':
    - Roadmap: 'roadmap.md'
    - Repositories: 's3gw-repos.md'
    - Contributing & reporting: 'contributing.md'
    - License: 'license.md'
  - 'Team decisions':
    - Use Markdown Any Decision Records: 'decisions/0000-use-markdown-any-decision-records.md'
theme: readthedocs
